#include "q4_3.hpp"
#include "digraph.h"
void q4_3()
{
    // TEST function generated by GPT
    try
    {
        Stack<int> s(5);

        cout << "Stack is empty: " << s.is_empty() << "\n";

        s.push(10);
        s.push(20);
        s.push(30);

        cout << "Top element: " << s.top() << "\n";
        cout << "Stack size: " << s.size() << "\n";

        s.pop();
        cout << "After popping, top element: " << s.top() << "\n";

        cout << "Stack is empty: " << s.is_empty() << "\n";
    }
    catch (const exception &e)
    {
        cerr << "Error: " << e.what() << "\n";
    }

    Digraph G;
    G.read("digraph2.txt");
    cout << "\n";
    cout << "Shortest directed paths from 1 to 91,...,100 in G2 (BFS):"
         << "\n";

    for (int w = 91; w <= 100; w++)
    {
        vector<int> path = G.path(1, w);
        if (path.size() == 0)
            cout << "No directed path from 1 to " << w << " exists.";
        for (size_t i = 0; i < path.size(); i++)
            cout << path[i] << " ";
        cout << "\n";
    }

    cout << "\n";
    cout << "Shortest directed paths from 1 to 91,...,100 in G2 (DFS_A):"
         << "\n";

    for (int w = 91; w <= 100; w++)
    {
        vector<int> path = G.path_dfs(1, w);
        if (path.size() == 0)
            cout << "No directed path from 1 to " << w << " exists.";
        for (size_t i = 0; i < path.size(); i++)
            cout << path[i] << " ";
        cout << "\n";
    }
}

// Comment on performance
/*
    Due to the nature of Depth first search, it does not  guarantee the shortest path to be found 
    between two nodes because it explores one branch of the graph deeply before moving to the next, 
    which can lead to suboptimal paths.

    BFS works best for shortest-path problems in  graphs, as it explores all nodes level by level, 
    guaranteeing the shortest path in terms of the number of edges.
*/