#include <iostream>
#include <cmath>

class QuadraticEquation
{
    double a{};
    double b{};
    double c{};
    mutable double D{};

public:
    QuadraticEquation() : a{1.0}, b{-2.0}, c{1.0} {}
    QuadraticEquation(double a, double b, double c) : a{a}, b{b}, c{c} {}

    void solve() const
    {
        print_input(); 
        if (no_solution())
        {
            std::cout << "There is no solution!\n";
        }
        else if (a == 0 && b == 0 && ((c >= -1e-10) && (c <= 1e-10)))
        {
            std::cout << "There is infinite number of solution!\n";
        }
        else if (a==0&&b!=0)
        {
            std::cout<<"The unique solution is "<<-c/b<<'\n';
        }
        else if (std::abs(D)<=1e-10)
        {
            std::cout<<"The unique solution is "<<-b/2/a<<'\n';
        }
        else
        {
            std::cout<<"x1 =  "<<(-b+std::sqrt(D))/2/a<<'\n';
            std::cout<<"x2 =  "<<(-b-sqrt(D))/2/a<<'\n';
        }
    }

private:
    double compute_determinant() const
    {
        return D = b * b - 4 * a * c;
    }

    bool no_solution() const
    {
        return (a == 0 && b == 0 && ((c < -1e-10) || (c > 1e-10))) || (compute_determinant() < -1e-10);
    }

    void print_input() const
    {
        std::cout << "a = " << a << '\n';
        std::cout << "b = " << b << '\n';
        std::cout << "c = " << c << '\n';
    }
};

int main()
{
    //Test Functions generated by ChatGPT
    QuadraticEquation q1;               // Default constructor
    q1.solve();
    std::cout<<std::endl;


    QuadraticEquation q2{1, 23, 2};     // Example with two solutions
    q2.solve();
    std::cout<<std::endl;


    QuadraticEquation q3{1, -2, 1};     // Example with one solution
    q3.solve();
    std::cout<<std::endl;


    QuadraticEquation q4{0, 0, 1};      // No solutions
    q4.solve();
    std::cout<<std::endl;


    QuadraticEquation q5{0, 0, 0};      // Infinite solutions
    q5.solve();
    std::cout<<std::endl;


    QuadraticEquation q6{0, 4, -8};     // Linear case
    q6.solve();
    std::cout<<std::endl;


    return 0;
}