#include <iostream>
#include <fstream>
#include <vector>
#include <list>
#include <set>

void findConnectedComponents(int numVertices, const std::vector<std::pair<int, int>> &edges)
{

    // Initialization
    std::vector<std::list<int>> L(numVertices);
    std::vector<int> C(numVertices);

    for (auto i = 0; i < numVertices; ++i)
    {
        L[i].push_back(i);
        C[i] = i;
    }

    // Process each edge
    for (const auto &edge : edges)
    {
        int a = edge.first;
        int b = edge.second;

        if (C[a] == C[b])
            continue;

        int oldComponent = C[a];
        for (int x : L[oldComponent])
        {
            C[x] = C[b];
        }

        L[C[b]].splice(L[C[b]].end(), L[oldComponent]);
    }

    std::set<int> uniqueComponents(C.begin(), C.end());
    std::cout << "Number of components: " << uniqueComponents.size() << std::endl;

    std::cout << "Components:\n";
    for (auto component : uniqueComponents)
    {
        std::cout << component + 1 << ": ";
        for (auto vertex : L[component])
        {
            std::cout << vertex + 1 << ", ";
        }
        std::cout << std::endl;
    }
}

int main()
{
    // File I/O Generated by ChatGPT
    std::ifstream inputFile("graph.txt");
    if (!inputFile)
    {
        std::cerr << "Error opening file!" << std::endl;
        return 1;
    }

    int numVertices;
    inputFile >> numVertices;

    std::vector<std::pair<int, int>> edges;
    int a, b;
    while (inputFile >> a >> b)
    {
        edges.emplace_back(a - 1, b - 1);
    }
    inputFile.close();

    findConnectedComponents(numVertices, edges);

    return 0;
}
