#include <cmath>
#include <iostream>
#include "linear_system.hpp"

LinearSystem::LinearSystem(std::vector<double> A, std::vector<double> b) : A(A), b(b) {} // Initializes A to A1 and b to b1

void LinearSystem::solve() const
{
    double det_A{sarrus_determinant(A)};
    if (std::abs(det_A) > 1e-10)
    {
        for (int col = 0; col < 3; ++col)
        {
            std::vector<double> A_replaced = A;
            for (int row = 0; row < 3; ++row)
            {
                A_replaced[row * 3 + col] = b[row];
            }
            sol.push_back(sarrus_determinant(A_replaced) / det_A);
        }
    }
}
// Sets sol to solution of Ax=b if abs(det(A))>1e/-10
// and sets sol to empty vector otherwise

void LinearSystem::print() const
{
    if (sol.size())
    {
        std::cout << "x = (" << sol[0] << ", " << sol[1] << ", " << sol[2] << ")`\n";
    }
    else
    {
        std::cout << "There is no unique solution!\n";
    }
}
// Prints solution to the screen;
// if sol is empty, then prints message to the
// screen that there is no unique solution

// Generated by GPT
double sarrus_determinant(const std::vector<double> &mat)
{
    // Ensure the input is of size 9 (3x3 matrix)
    if (mat.size() != 9)
    {
        throw std::logic_error("Matrix must be 3x3 (9 elements).");
    }

    // Extract elements of the matrix
    double a = mat[0], b = mat[1], c = mat[2];
    double d = mat[3], e = mat[4], f = mat[5];
    double g = mat[6], h = mat[7], i = mat[8];

    return a * e * i + b * f * g + c * d * h - c * e * g - b * d * i - a * f * h;
    ;
}