#include "q5_1.hpp"
#include <limits>
#include <iostream>

// Transfers rate curve data into separate date and rate vectors.
void transfer_ratecurve(std::vector<int> &dates, std::vector<double> &rates,
                        const RateCurve &rc)
{
    if (dates.size() != rc.size() || rates.size() != rc.size()) {
        std::cerr << "Error: Vectors not resized properly!" << std::endl;
        return;
    }

    for (auto i = 0; i < rc.size(); ++i)
    {
        auto [d, r] = rc[i];
        dates[i] = d;
        rates[i] = r;
    }
}

double YieldCurve::interpolate(const std::vector<int> &dates,
                               const std::vector<double> &rates, const int date)
{
    if (dates.empty() || rates.empty())
    {
        std::cerr << "Error: Dates or rates vector is empty!" << std::endl;
        return std::numeric_limits<double>::quiet_NaN();
    }

    // Handle edge cases where date is outside the range of the provided curve
    if (date <= dates.front())
    {
        return rates.front();
    }
    if (date >= dates.back())
    {
        return rates.back();
    }

    // Perform linear interpolation for date within the range
    for (size_t i = 0; i < dates.size() - 1; ++i)
    {
        if (date >= dates[i] && date <= dates[i + 1])
        {
            double d1 = dates[i];
            double d2 = dates[i + 1];
            double r1 = rates[i];
            double r2 = rates[i + 1];
            return r1 + (r2 - r1) * (date - d1) / (d2 - d1);
        }
    }

    // Return NaN if input is incorrect and date does not fit logically.
    return std::numeric_limits<double>::quiet_NaN();
}

auto FixRatedBond::get_df(const int end, int today)
{
    std::vector<int> dates(IC.size());
    std::vector<double> rates(IC.size());

    // Transfer rate curve data from associated YieldCurve instance
    transfer_ratecurve(dates, rates, IC);

    double rate = y_curve->interpolate(dates, rates, end);
    double df = std::exp(-(end - today) / 365.0 * rate / 100.0);
    return df;
}

// Get payment date and corresponding discount factor
std::tuple<int, double> FixRatedBond::calculate_date_df(int today, int i, int frequency)
{
    int payment_date = today + (i + 1) * 365 / frequency;
    double df = get_df(payment_date, today);
    return std::make_tuple(payment_date, df);
}

// getCouponFrequencyValue Generated By ChatGPT
int FixRatedBond::getCouponFrequencyValue(const std::string &input)
{
    int k;
    if (input == "A")
    {
        k = 1;
    }
    else if (input == "S")
    {
        k = 2;
    }
    else if (input == "Q")
    {
        k = 4;
    }
    else
    {
        std::cerr << "Invalid input!" << std::endl;
        k = -1; // or handle error as needed
    }
    return k;
}

// Calculate bond price using zero-coupon discounting
double FixRatedBond::bond_price_zero() {
    // Get coupon payment frequency (e.g., Annual, Semi-Annual, Quarterly)
    int frequency = getCouponFrequencyValue(payment_schedule);
    if (frequency <= 0) {
        std::cerr << "Invalid coupon frequency value." << std::endl;
        return -1.0; // Indicate error
    }

    // Calculate the number of coupon payments
    int num_payments = static_cast<int>(frequency * maturity);

    // Prepare storage for payment dates and discount factors
    std::vector<std::tuple<int, double>> date_bond_price_vector(num_payments);

    // Populate date-bond price vector for all payment dates except the last one
    for (int i = 0; i < num_payments - 1; ++i) {
        date_bond_price_vector[i] = calculate_date_df(today, i, frequency);
    }

    // Handle final payment
    int final_payment_date = today + static_cast<int>(maturity * 365);
    double final_df = get_df(final_payment_date, today);
    date_bond_price_vector.back() = std::make_tuple(final_payment_date, final_df);

    // Compute total bond price
    double total_price = 0.0;
    for (const auto &tp : date_bond_price_vector) {
        int date = std::get<0>(tp);
        double df = std::get<1>(tp);
        double payment = (date == final_payment_date)
                             ? face_value * (1 + coupon_rate / frequency)
                             : (face_value * coupon_rate / frequency);
        total_price += payment * df;
    }

    return total_price;
}

void q5_1() {
    auto yield_curve = std::make_shared<YieldCurve>(IC);

    FixRatedBond bond1(yield_curve, 100.0, 0.02, 4.0, "Q", 41082, 0.0);
    FixRatedBond bond2(yield_curve, 100.0, 0.03, 2.0, "S", 41082, 0.0);
    FixRatedBond bond3(yield_curve, 100.0, 0.04, 3.0, "A", 41082, 0.0);

    double v00 = bond1.bond_price_zero();
    std::cout << "v00: " << v00 << std::endl; //v00: 100.579

    double v01 = bond2.bond_price_zero();
    std::cout << "v01: " << v01 <<  std::endl; // v01: 103.281

    double v02 = bond3.bond_price_zero();
    std::cout << "v02: " << v02 << std::endl; // v02: 106.992
}
