#include "q5_3.hpp"
#include <stdexcept>
#include <iostream>
#include <iomanip>
#include <sstream>


// Alert: use std::move explicitly to avoid misuse of move method!!!
ShapeCollection &ShapeCollection::add(unique_ptr<Shape> S)
{
    elements.emplace_back(std::move(S));  
    return *this; 
}

ShapeCollection &ShapeCollection::remove(size_t i)
{
    if (i >= elements.size())
    {
        throw out_of_range("Index out of range for removal.");
    }
    elements.erase(elements.begin() + i);  
    return *this;
}

ShapeCollection &ShapeCollection::move(const Coord &offset)
{
    for (auto &shape : elements)
    {
        shape->move(offset);
    }
    return *this;
}

// os stream operator overloading generated by GPT

// Helper function to format Coord
string formatCoord(const Coord &coord)
{
    ostringstream oss;
    oss << "(" << coord.get_x() << "," << coord.get_y() << ")";
    return oss.str();
}

// Rectangle operator<<
ostream &operator<<(ostream &os, const Rectangle &rect)
{
    // Calculate rectangle's four corners
    Coord bottomLeft = rect.anchorPoint;
    Coord bottomRight = Coord(rect.anchorPoint.get_x() + rect.width, rect.anchorPoint.get_y());
    Coord topRight = Coord(rect.anchorPoint.get_x() + rect.width, rect.anchorPoint.get_y() + rect.height);
    Coord topLeft = Coord(rect.anchorPoint.get_x(), rect.anchorPoint.get_y() + rect.height);

    os << "Rectangle@[("
       << formatCoord(bottomLeft) << " "
       << formatCoord(bottomRight) << " "
       << formatCoord(topRight) << " "
       << formatCoord(topLeft) << ")]";

    return os;
}

// Circle operator<<
ostream &operator<<(ostream &os, const Circle &circle)
{
    os << "Circle@(" << formatCoord(circle.anchorPoint) << ", r=" << circle.radius << ")";
    return os;
}

// ShapeCollection operator<<
ostream &operator<<(ostream &os, const ShapeCollection &collection)
{
    os << "ShapeCollection: [";

    for (size_t i = 0; i < collection.elements.size(); ++i)
    {
        if (i > 0)
        {
            os << ", ";
        }

        // Dynamically cast the shape to determine its actual type
        if (auto rect = dynamic_cast<Rectangle *>(collection.elements[i].get()))
        {
            os << *rect;
        }
        else if (auto circ = dynamic_cast<Circle *>(collection.elements[i].get()))
        {
            os << *circ;
        }
    }

    os << "]";

    return os;
}

void testCoord()
{
    cout << "Testing Coord..." << endl;

    Coord c1(1.0, 2.0);
    Coord c2(3.0, 4.0);
    Coord c3 = c1 + c2;

    assert(c3.get_x() == 4.0);
    assert(c3.get_y() == 6.0);

    c1 += c2;
    assert(c1.get_x() == 4.0);
    assert(c1.get_y() == 6.0);

    assert(!(c1 == c2));
    assert(c1 == c3);

    cout << "Coord tests passed!" << endl;
}

void testRectangle()
{
    cout << "Testing Rectangle..." << endl;

    Rectangle rect(Coord(1.0, 1.0), 2.0, 3.0);
    cout << rect << endl;
    assert(rect.getAnchorPoint().get_x() == 1.0);
    assert(rect.getAnchorPoint().get_y() == 1.0);

    rect.move(Coord(1.0, 1.0));
    assert(rect.getAnchorPoint().get_x() == 2.0);
    assert(rect.getAnchorPoint().get_y() == 2.0);

    cout << "Rectangle tests passed!" << endl;
}

void testCircle()
{
    cout << "Testing Circle..." << endl;

    Circle circ(Coord(2.0, 2.0), 1.0);
    cout << circ << endl;

    assert(circ.getAnchorPoint().get_x() == 2.0);
    assert(circ.getAnchorPoint().get_y() == 2.0);

    circ.move(Coord(1.0, 1.0));
    assert(circ.getAnchorPoint().get_x() == 3.0);
    assert(circ.getAnchorPoint().get_y() == 3.0);

    cout << "Circle tests passed!" << endl;
}

void testShapeCollection()
{
    cout << "Testing ShapeCollection..." << endl;

    unique_ptr<Shape> rect = make_unique<Rectangle>(Coord(1.0, 1.0), 2.0, 3.0);
    unique_ptr<Shape> circ = make_unique<Circle>(Coord(2.0, 2.0), 1.0);

    ShapeCollection collection(make_unique<Rectangle>(Coord(0, 0), 1.0, 1.0));
    collection.add(std::move(rect)).add(std::move(circ));

    assert(collection.size() == 3);

    cout << collection << endl;

    collection.move(Coord(1.0, 1.0));
    cout << "After moving:" << endl;
    cout << collection << endl;

    collection.remove(1);
    assert(collection.size() == 2);

    cout << "ShapeCollection tests passed!" << endl;
}


void q5_3()
{
    testCoord();
    testRectangle();
    testCircle();
    testShapeCollection();
    cout << "All tests passed!" << endl;

}

