#include "q3_7.hpp"
#include <cmath>
#include <iostream>
#include <string>
#include <tuple>
#include <algorithm>
#include <vector>
#include <cassert>
#include <numeric>

// getCouponFrequencyValue Generated By ChatGPT
int getCouponFrequencyValue(const std::string& input) {
    int k;
    if (input == "A") {
        k = 1;
    } else if (input == "S") {
        k = 2;
    } else if (input == "Q") {
        k = 4;
    } else {
        std::cerr << "Invalid input!" << std::endl;
        k = -1; // or handle error as needed
    }
    return k;
}

// Calculate discount factor
auto get_df(const int end, int today) {

  std::vector<int> dates(IC.size(), 0);
  std::vector<double> rates(IC.size(), 0.0);

  transfer_ratecurve(dates, rates, IC);

  double r = interpolate(dates, rates, end);
  double d = std::exp(-(end - today) / 365.0 * r / 100.0);
  return d;
}



std::tuple<int, double> calculate_date_df(int today, int i, int frequency) {
    int payment_date = today + (i + 1) * 365 / frequency;
    double df = get_df(payment_date, today);
    return std::make_tuple(payment_date, df);
}


double bond_price_zero(double face_value, double coupon_rate, double maturity,
                       std::string ps, int today, double ic_spread) {
  
    int frequency = getCouponFrequencyValue(ps);

    int num_payments = frequency * maturity;
  
    std::vector<std::tuple<int, double>> date_bond_price_vector(num_payments);

    std::generate(date_bond_price_vector.begin(), date_bond_price_vector.end() - 1,
                  [today, frequency, i = 0]() mutable {
                      return calculate_date_df(today, i++, frequency);
                  });

    int final_payment_date = today + maturity * 365;
    double final_df = get_df(final_payment_date, today);
    date_bond_price_vector.back() = std::make_tuple(final_payment_date, final_df);

    double total_price = 0.0;
    std::for_each(date_bond_price_vector.begin(), date_bond_price_vector.end(),
                  [&total_price, face_value, coupon_rate, frequency, final_payment_date](const std::tuple<int, double>& tp) {
                      int date = std::get<0>(tp);
                      double df = std::get<1>(tp);
                      double payment = (date == final_payment_date) ? face_value*(1+coupon_rate/frequency) : (face_value * coupon_rate / frequency);
                      total_price += payment * df;
                  });

    return total_price;
}


void q4_10()
{
  auto v00 = bond_price_zero(100, 0.02, 4, "Q", 41082,0.0);
  std::cout << "v00: " << v00 << "\n"; // v00: 100.579
  auto v01 = bond_price_zero(100, 0.03, 2, "S", 41082, 0.0);
  std::cout << "v01: " << v01 << "\n"; // v01: 103.281
  auto v02 = bond_price_zero(100, 0.04, 3, "A", 41082, 0.0);
  std::cout << "v02: " << v02 << "\n"; // v02: 106.992
}