#include <cassert>
#include <chrono>
#include <functional>
#include <iostream>
#include <vector>

void q4_2(int n, int k) {

  if (n < 0 || k < 0) {
    std::cout << "Invalid input: n and k must be non-negative integers."
              << std::endl;
    return;
  }

  std::function<int(int, int)> P = [&P](int n, int k) {
    if (k < 1 || n < 0) {
      return 0;
    } else if (n == 0) {
      return 1;
    } else {
      return P(n, k - 1) + P(n - k, k);
    }
  };

  std::vector<std::vector<int>> memo_vec;
  const int NOT_COMPUTED{-1};
  memo_vec.resize(n + 1, std::vector<int>(n + 1, NOT_COMPUTED));

  std::function<int(int, int)> P_mem = [&P_mem, &memo_vec](int n, int k) {
    if (k < 1 || n < 0) {
      return 0;
    } else if (n == 0) {
      return 1;
    } else {
      if (memo_vec[n][k] != NOT_COMPUTED)
        return memo_vec[n][k];
      memo_vec[n][k] = P_mem(n, k - 1) + P_mem(n - k, k);
      return memo_vec[n][k];
    }
  };

  std::cout << "Recursion without memorization:\n";

  auto start_time_no_memo = std::chrono::high_resolution_clock::now();
  int result_no_memo = P(n, k);
  auto end_time_no_memo = std::chrono::high_resolution_clock::now();
  std::chrono::duration<double> duration_no_memo =
      end_time_no_memo - start_time_no_memo;
  std::cout << "P(" << n << ',' << k << ") = " << result_no_memo << "\n";
  std::cout << "Time taken (no memoization): " << duration_no_memo.count()
            << " seconds\n";

  std::cout << "Recursion with memorization:\n";

  auto start_time_memo = std::chrono::high_resolution_clock::now();
  int result_memo = P_mem(n, k);
  auto end_time_memo = std::chrono::high_resolution_clock::now();
  std::chrono::duration<double> duration_memo = end_time_memo - start_time_memo;
  std::cout << "P_mem(" << n << ',' << k << ") = " << result_memo << "\n";
  std::cout << "Time taken (with memoization): " << duration_memo.count()
            << " seconds\n";

  assert(result_no_memo == result_memo &&
         "Recursion result differs from memorized result!");
}

// TIMING FUNCTIONALITY GENERATED BY CHATGPT
