#include "q3_7.hpp"
#include <iostream>
#include <vector>
#include <tuple>
#include <algorithm>
#include <numeric>
#include <cmath>
#include <iomanip>  // For formatting output

// Helper function to print RateCurve 
// Generated by ChatGPT
void print_rate_curve(const RateCurve& curve, const std::string& name) {
    std::cout << name << ":\n";
    for (const auto& [date, rate] : curve) {
        std::cout << "Date: " << date << ", Rate: " << std::fixed << std::setprecision(4) << rate << '\n';
    }
    std::cout << '\n';
}


double get_maturity_in_years(int date, int today) {
    return (date - today) / 365.0;
}

RateCurve parallel_updown(double delta, int today, const RateCurve &IC) {
    RateCurve result(IC.size());

    std::transform(IC.begin(), IC.end(), result.begin(),
                   [delta](const std::tuple<int, double>& rate) {
                       return std::make_tuple(std::get<0>(rate), std::get<1>(rate) + delta);
                   });

    return result;
}


RateCurve short_rates_shock(double delta, int today, const RateCurve &IC) {
    RateCurve result(IC.size());

    std::transform(IC.begin(), IC.end(), result.begin(),
                   [delta, today](const std::tuple<int, double>& rate) {
                       double maturity_in_years = get_maturity_in_years(std::get<0>(rate), today);
                       double shock = delta * std::exp(-maturity_in_years / 4.0);
                       return std::make_tuple(std::get<0>(rate), std::get<1>(rate) + shock);
                   });

    return result;
}

RateCurve rotational_shock(double delta, int today, const RateCurve &IC) {
    RateCurve result(IC.size());

    std::transform(IC.begin(), IC.end(), result.begin(),
                   [delta , today](const std::tuple<int, double>& rate) {
                       double maturity_in_years = get_maturity_in_years(std::get<0>(rate), today);
                       double short_rate_shock = (maturity_in_years < 1.0) ? delta * std::exp(-maturity_in_years / 4.0) : 0.0;
                       double long_rate_shock = (maturity_in_years >= 1.0) ? delta * (1.0 - std::exp(-maturity_in_years / 4.0)) : 0.0;
                       double total_shock = short_rate_shock + long_rate_shock;
                       return std::make_tuple(std::get<0>(rate), std::get<1>(rate) + total_shock);
                   });

    return result;
}

void q5_3()
{
  // Due to time being, for shock down/up, a up/down indicator should be better implemented, current version use postive        // delta to show up and negtive delta to show down.
  
  double delta1 = 0.03; // For short rates shock
  double delta2 = 0.02; // For parallel shock
  double delta3 = 0.015; // For rotational shock
  int today = 41082; 
  // Print original rate curve
  print_rate_curve(IC, "Original Rate Curve");
  
  // Compute shocked curves
  RateCurve parallel_shocked_curve = parallel_updown(delta2, today, IC);
  RateCurve short_rates_shocked_curve = short_rates_shock(delta1, today, IC);
  RateCurve rotational_shocked_curve = rotational_shock(delta3, today, IC);

  // Print shocked curves
  print_rate_curve(parallel_shocked_curve, "Parallel Shocked Curve");
  print_rate_curve(short_rates_shocked_curve, "Short Rates Shocked Curve");
  print_rate_curve(rotational_shocked_curve, "Rotational Shocked Curve");



}



